[package]
name = "vapi-client"
version = "0.1.3"
authors = ["OpenAPI Generator team and contributors", "Nikolas Yanek-Chrones"]
description = "Voice AI for developers."
homepage = "https://docs.vapi.ai"
repository = "https://github.com/nikothomas/vapi-client"
keywords = ["vapi", "api", "client"]
categories = ["api-bindings"]
readme = "README.md"
# Override this license by providing a License Object in the OpenAPI.
license = "MIT"
edition = "2024"


[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
async-trait = "^0.1"
reqwest = { version = "^0.12", features = ["json", "multipart"] }
bon = { version = "3.5.1", optional = true }
utoipa = "5.3.1"
regex = "1.11.1"
[features]
bon = ["dep:bon"]

[[bin]]
path = "src/bin/script.rs"
name = "openapi"