/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

use super::{configuration, Error};
use crate::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait LogsApi: Send + Sync {
    /// DELETE /logs
    async fn logging_controller_logs_delete_query<
        'r_type,
        'assistant_id,
        'phone_number_id,
        'customer_id,
        'squad_id,
        'call_id,
    >(
        &self,
        r#type: Option<&'r_type str>,
        assistant_id: Option<&'assistant_id str>,
        phone_number_id: Option<&'phone_number_id str>,
        customer_id: Option<&'customer_id str>,
        squad_id: Option<&'squad_id str>,
        call_id: Option<&'call_id str>,
    ) -> Result<(), Error<LoggingControllerLogsDeleteQueryError>>;

    /// GET /logs
    async fn logging_controller_logs_query<
        'r_type,
        'webhook_type,
        'assistant_id,
        'phone_number_id,
        'customer_id,
        'squad_id,
        'call_id,
        'page,
        'sort_order,
        'limit,
        'created_at_gt,
        'created_at_lt,
        'created_at_ge,
        'created_at_le,
        'updated_at_gt,
        'updated_at_lt,
        'updated_at_ge,
        'updated_at_le,
    >(
        &self,
        r#type: Option<&'r_type str>,
        webhook_type: Option<&'webhook_type str>,
        assistant_id: Option<&'assistant_id str>,
        phone_number_id: Option<&'phone_number_id str>,
        customer_id: Option<&'customer_id str>,
        squad_id: Option<&'squad_id str>,
        call_id: Option<&'call_id str>,
        page: Option<f64>,
        sort_order: Option<&'sort_order str>,
        limit: Option<f64>,
        created_at_gt: Option<String>,
        created_at_lt: Option<String>,
        created_at_ge: Option<String>,
        created_at_le: Option<String>,
        updated_at_gt: Option<String>,
        updated_at_lt: Option<String>,
        updated_at_ge: Option<String>,
        updated_at_le: Option<String>,
    ) -> Result<models::LogsPaginatedResponse, Error<LoggingControllerLogsQueryError>>;
}

pub struct LogsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl LogsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl LogsApi for LogsApiClient {
    async fn logging_controller_logs_delete_query<
        'r_type,
        'assistant_id,
        'phone_number_id,
        'customer_id,
        'squad_id,
        'call_id,
    >(
        &self,
        r#type: Option<&'r_type str>,
        assistant_id: Option<&'assistant_id str>,
        phone_number_id: Option<&'phone_number_id str>,
        customer_id: Option<&'customer_id str>,
        squad_id: Option<&'squad_id str>,
        call_id: Option<&'call_id str>,
    ) -> Result<(), Error<LoggingControllerLogsDeleteQueryError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/logs", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = r#type {
            local_var_req_builder =
                local_var_req_builder.query(&[("type", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = assistant_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("assistantId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = phone_number_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("phoneNumberId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = customer_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("customerId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = squad_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("squadId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = call_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("callId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<LoggingControllerLogsDeleteQueryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn logging_controller_logs_query<
        'r_type,
        'webhook_type,
        'assistant_id,
        'phone_number_id,
        'customer_id,
        'squad_id,
        'call_id,
        'page,
        'sort_order,
        'limit,
        'created_at_gt,
        'created_at_lt,
        'created_at_ge,
        'created_at_le,
        'updated_at_gt,
        'updated_at_lt,
        'updated_at_ge,
        'updated_at_le,
    >(
        &self,
        r#type: Option<&'r_type str>,
        webhook_type: Option<&'webhook_type str>,
        assistant_id: Option<&'assistant_id str>,
        phone_number_id: Option<&'phone_number_id str>,
        customer_id: Option<&'customer_id str>,
        squad_id: Option<&'squad_id str>,
        call_id: Option<&'call_id str>,
        page: Option<f64>,
        sort_order: Option<&'sort_order str>,
        limit: Option<f64>,
        created_at_gt: Option<String>,
        created_at_lt: Option<String>,
        created_at_ge: Option<String>,
        created_at_le: Option<String>,
        updated_at_gt: Option<String>,
        updated_at_lt: Option<String>,
        updated_at_ge: Option<String>,
        updated_at_le: Option<String>,
    ) -> Result<models::LogsPaginatedResponse, Error<LoggingControllerLogsQueryError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/logs", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = r#type {
            local_var_req_builder =
                local_var_req_builder.query(&[("type", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = webhook_type {
            local_var_req_builder =
                local_var_req_builder.query(&[("webhookType", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = assistant_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("assistantId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = phone_number_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("phoneNumberId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = customer_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("customerId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = squad_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("squadId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = call_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("callId", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = sort_order {
            local_var_req_builder =
                local_var_req_builder.query(&[("sortOrder", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = created_at_gt {
            local_var_req_builder =
                local_var_req_builder.query(&[("createdAtGt", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = created_at_lt {
            local_var_req_builder =
                local_var_req_builder.query(&[("createdAtLt", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = created_at_ge {
            local_var_req_builder =
                local_var_req_builder.query(&[("createdAtGe", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = created_at_le {
            local_var_req_builder =
                local_var_req_builder.query(&[("createdAtLe", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = updated_at_gt {
            local_var_req_builder =
                local_var_req_builder.query(&[("updatedAtGt", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = updated_at_lt {
            local_var_req_builder =
                local_var_req_builder.query(&[("updatedAtLt", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = updated_at_ge {
            local_var_req_builder =
                local_var_req_builder.query(&[("updatedAtGe", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = updated_at_le {
            local_var_req_builder =
                local_var_req_builder.query(&[("updatedAtLe", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::LogsPaginatedResponse`",
                    )))
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::LogsPaginatedResponse`"
                    ))))
                }
            }
        } else {
            let local_var_entity: Option<LoggingControllerLogsQueryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`logging_controller_logs_delete_query`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LoggingControllerLogsDeleteQueryError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`logging_controller_logs_query`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LoggingControllerLogsQueryError {
    UnknownValue(serde_json::Value),
}
