/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsGetRequest {
    /// This is the list of metric queries you want to perform.
    #[serde(rename = "queries")]
    pub queries: Vec<models::AnalyticsQuery>,
}

impl AnalyticsGetRequest {
    pub fn new(queries: Vec<models::AnalyticsQuery>) -> AnalyticsGetRequest {
        AnalyticsGetRequest {
            queries,
        }
    }
}

