/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnthropicModelModel : The specific Anthropic/Claude model that will be used.
/// The specific Anthropic/Claude model that will be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AnthropicModelModel {
    #[serde(rename = "claude-3-opus-20240229")]
    Claude3Opus20240229,
    #[serde(rename = "claude-3-sonnet-20240229")]
    Claude3Sonnet20240229,
    #[serde(rename = "claude-3-haiku-20240307")]
    Claude3Haiku20240307,
    #[serde(rename = "claude-3-5-sonnet-20240620")]
    Claude35Sonnet20240620,
    #[serde(rename = "claude-3-5-sonnet-20241022")]
    Claude35Sonnet20241022,
    #[serde(rename = "claude-3-5-haiku-20241022")]
    Claude35Haiku20241022,
    #[serde(rename = "claude-3-7-sonnet-20250219")]
    Claude37Sonnet20250219,

}

impl std::fmt::Display for AnthropicModelModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Claude3Opus20240229 => write!(f, "claude-3-opus-20240229"),
            Self::Claude3Sonnet20240229 => write!(f, "claude-3-sonnet-20240229"),
            Self::Claude3Haiku20240307 => write!(f, "claude-3-haiku-20240307"),
            Self::Claude35Sonnet20240620 => write!(f, "claude-3-5-sonnet-20240620"),
            Self::Claude35Sonnet20241022 => write!(f, "claude-3-5-sonnet-20241022"),
            Self::Claude35Haiku20241022 => write!(f, "claude-3-5-haiku-20241022"),
            Self::Claude37Sonnet20250219 => write!(f, "claude-3-7-sonnet-20250219"),
        }
    }
}

impl Default for AnthropicModelModel {
    fn default() -> AnthropicModelModel {
        Self::Claude3Opus20240229
    }
}

