/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiRequestMethod {
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "GET")]
    Get,

}

impl std::fmt::Display for ApiRequestMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Post => write!(f, "POST"),
            Self::Get => write!(f, "GET"),
        }
    }
}

impl Default for ApiRequestMethod {
    fn default() -> ApiRequestMethod {
        Self::Post
    }
}

