/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureVoiceId : This is the provider-specific ID that will be used.
/// This is the provider-specific ID that will be used.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AzureVoiceId {
    AzureVoiceIdEnum(models::AzureVoiceIdEnum),
    String(String),
}

impl Default for AzureVoiceId {
    fn default() -> Self {
        Self::AzureVoiceIdEnum(Default::default())
    }
}

