/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackoffPlan {
    /// This is the maximum number of retries to attempt if the request fails. Defaults to 0 (no retries).  @default 0
    #[serde(rename = "maxRetries")]
    pub max_retries: f64,
    /// This is the type of backoff plan to use. Defaults to fixed.  @default fixed
    #[serde(rename = "type")]
    pub r#type: std::collections::HashMap<String, serde_json::Value>,
    /// This is the base delay in seconds. For linear backoff, this is the delay between each retry. For exponential backoff, this is the initial delay.
    #[serde(rename = "baseDelaySeconds")]
    pub base_delay_seconds: f64,
}

impl BackoffPlan {
    pub fn new(max_retries: f64, r#type: std::collections::HashMap<String, serde_json::Value>, base_delay_seconds: f64) -> BackoffPlan {
        BackoffPlan {
            max_retries,
            r#type,
            base_delay_seconds,
        }
    }
}

