/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatInput : This is the input text for the chat. Can be a string or an array of chat messages.
/// This is the input text for the chat. Can be a string or an array of chat messages.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatInput {
    String(String),
    MessageArray(Vec<models::MessageArrayInner>),
}

impl Default for ChatInput {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

