/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientMessageMessage : These are all the messages that can be sent to the client-side SDKs during the call. Configure the messages you'd like to receive in `assistant.clientMessages`.
/// These are all the messages that can be sent to the client-side SDKs during the call. Configure the messages you'd like to receive in `assistant.clientMessages`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClientMessageMessage {
    ClientMessageWorkflowNodeStarted(Box<models::ClientMessageWorkflowNodeStarted>),
    ClientMessageConversationUpdate(Box<models::ClientMessageConversationUpdate>),
    ClientMessageHang(Box<models::ClientMessageHang>),
    ClientMessageMetadata(Box<models::ClientMessageMetadata>),
    ClientMessageModelOutput(Box<models::ClientMessageModelOutput>),
    ClientMessageSpeechUpdate(Box<models::ClientMessageSpeechUpdate>),
    ClientMessageTranscript(Box<models::ClientMessageTranscript>),
    ClientMessageToolCalls(Box<models::ClientMessageToolCalls>),
    ClientMessageToolCallsResult(Box<models::ClientMessageToolCallsResult>),
    ClientMessageTransferUpdate(Box<models::ClientMessageTransferUpdate>),
    ClientMessageUserInterrupted(Box<models::ClientMessageUserInterrupted>),
    ClientMessageLanguageChangeDetected(Box<models::ClientMessageLanguageChangeDetected>),
    ClientMessageVoiceInput(Box<models::ClientMessageVoiceInput>),
}

impl Default for ClientMessageMessage {
    fn default() -> Self {
        Self::ClientMessageWorkflowNodeStarted(Default::default())
    }
}

