/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientInboundMessageMessageOneOf2 {
    /// This is the content to say.
    #[serde(rename = "content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    /// This is the flag to end call after content is spoken.
    #[serde(rename = "endCallAfterSpoken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_call_after_spoken: Option<Option<bool>>,
    /// This is the flag for whether the message is interruptible.
    #[serde(rename = "interruptionsEnabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interruptions_enabled: Option<Option<bool>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ClientInboundMessageMessageOneOf2 {
    pub fn new(r#type: Type) -> ClientInboundMessageMessageOneOf2 {
        ClientInboundMessageMessageOneOf2 {
            content: None,
            end_call_after_spoken: None,
            interruptions_enabled: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "say")]
    Say,
}

impl Default for Type {
    fn default() -> Type {
        Self::Say
    }
}

