/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientInboundMessageMessageOneOf3 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ClientInboundMessageMessageOneOf3 {
    pub fn new(r#type: Type) -> ClientInboundMessageMessageOneOf3 {
        ClientInboundMessageMessageOneOf3 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "end-call")]
    EndCall,
}

impl Default for Type {
    fn default() -> Type {
        Self::EndCall
    }
}

