/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientMessage {
    #[serde(rename = "message")]
    pub message: Box<models::ClientMessageMessage>,
}

impl ClientMessage {
    pub fn new(message: models::ClientMessageMessage) -> ClientMessage {
        ClientMessage {
            message: Box::new(message),
        }
    }
}

