/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientInboundMessage {
    #[serde(rename = "message")]
    pub message: models::ClientInboundMessageMessage,
}

impl ClientInboundMessage {
    pub fn new(message: models::ClientInboundMessageMessage) -> ClientInboundMessage {
        ClientInboundMessage {
            message,
        }
    }
}

