/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientMessageConversationUpdate {
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<models::ClientMessageWorkflowNodeStartedPhoneNumber>,
    /// This is the type of the message. \"conversation-update\" is sent when an update is committed to the conversation history.
    #[serde(rename = "type")]
    pub r#type: TypeTrue,
    /// This is the most up-to-date conversation history at the time the message is sent.
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<models::ArtifactMessagesInner>>,
    /// This is the most up-to-date conversation history at the time the message is sent, formatted for OpenAI.
    #[serde(rename = "messagesOpenAIFormatted")]
    pub messages_open_ai_formatted: Vec<models::OpenAiMessage>,
    /// This is the timestamp of the message.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
    /// This is the call that the message is associated with.
    #[serde(rename = "call", skip_serializing_if = "Option::is_none")]
    pub call: Option<models::Call>,
    /// This is the customer that the message is associated with.
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<models::CreateCustomerDto>,
    /// This is the assistant that the message is associated with.
    #[serde(rename = "assistant", skip_serializing_if = "Option::is_none")]
    pub assistant: Option<models::CreateAssistantDto>,
}

impl ClientMessageConversationUpdate {
    pub fn new(
        r#type: TypeTrue,
        messages_open_ai_formatted: Vec<models::OpenAiMessage>,
    ) -> ClientMessageConversationUpdate {
        ClientMessageConversationUpdate {
            phone_number: None,
            r#type,
            messages: None,
            messages_open_ai_formatted,
            timestamp: None,
            call: None,
            customer: None,
            assistant: None,
        }
    }
}
/// This is the type of the message. \"conversation-update\" is sent when an update is committed to the conversation history.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeTrue {
    #[serde(rename = "conversation-update")]
    ConversationUpdate,
}

impl Default for TypeTrue {
    fn default() -> TypeTrue {
        Self::ConversationUpdate
    }
}
