/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudflareCredential {
    /// Credential provider. Only allowed value is cloudflare
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// Cloudflare Account Id.
    #[serde(rename = "accountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<Option<String>>,
    /// Cloudflare API Key / Token.
    #[serde(rename = "apiKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Option<String>>,
    /// Cloudflare Account Email.
    #[serde(rename = "accountEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_email: Option<Option<String>>,
    /// This is the unique identifier for the credential.
    #[serde(rename = "id")]
    pub id: String,
    /// This is the unique identifier for the org that this credential belongs to.
    #[serde(rename = "orgId")]
    pub org_id: String,
    /// This is the ISO 8601 date-time string of when the credential was created.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// This is the ISO 8601 date-time string of when the assistant was last updated.
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// This is the name of credential. This is just for your reference.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "bucketPlan", skip_serializing_if = "Option::is_none")]
    pub bucket_plan: Option<models::CloudflareR2BucketPlan>,
}

impl CloudflareCredential {
    pub fn new(provider: Provider, id: String, org_id: String, created_at: String, updated_at: String) -> CloudflareCredential {
        CloudflareCredential {
            provider,
            account_id: None,
            api_key: None,
            account_email: None,
            id,
            org_id,
            created_at,
            updated_at,
            name: None,
            bucket_plan: None,
        }
    }
}
/// Credential provider. Only allowed value is cloudflare
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "cloudflare")]
    Cloudflare,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Cloudflare
    }
}

