/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateChatDtoInput : This is the input text for the chat. Can be a string or an array of chat messages. This field is REQUIRED for chat creation.
/// This is the input text for the chat. Can be a string or an array of chat messages. This field is REQUIRED for chat creation.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateChatDtoInput {
    String(String),
    MessageArray(Vec<models::MessageArrayInner>),
}

impl Default for CreateChatDtoInput {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
