/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateToolTemplateDtoProviderDetails {
    MakeToolProviderDetails(models::MakeToolProviderDetails),
    GhlToolProviderDetails(models::GhlToolProviderDetails),
    FunctionToolProviderDetails(models::FunctionToolProviderDetails),
    GoogleCalendarCreateEventToolProviderDetails(models::GoogleCalendarCreateEventToolProviderDetails),
    GoogleSheetsRowAppendToolProviderDetails(models::GoogleSheetsRowAppendToolProviderDetails),
}

impl Default for CreateToolTemplateDtoProviderDetails {
    fn default() -> Self {
        Self::MakeToolProviderDetails(Default::default())
    }
}
/// The type of tool. \"make\" for Make tool.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "make")]
    Make,
    #[serde(rename = "ghl")]
    Ghl,
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "google.calendar.event.create")]
    GooglePeriodCalendarPeriodEventPeriodCreate,
    #[serde(rename = "google.sheets.row.append")]
    GooglePeriodSheetsPeriodRowPeriodAppend,
}

impl Default for Type {
    fn default() -> Type {
        Self::Make
    }
}

