/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreateAzureOpenAiCredentialDtoRegion {
    #[serde(rename = "australia")]
    Australia,
    #[serde(rename = "canadaeast")]
    Canadaeast,
    #[serde(rename = "canadacentral")]
    Canadacentral,
    #[serde(rename = "eastus2")]
    Eastus2,
    #[serde(rename = "eastus")]
    Eastus,
    #[serde(rename = "france")]
    France,
    #[serde(rename = "india")]
    India,
    #[serde(rename = "japaneast")]
    Japaneast,
    #[serde(rename = "japanwest")]
    Japanwest,
    #[serde(rename = "uaenorth")]
    Uaenorth,
    #[serde(rename = "northcentralus")]
    Northcentralus,
    #[serde(rename = "norway")]
    Norway,
    #[serde(rename = "southcentralus")]
    Southcentralus,
    #[serde(rename = "swedencentral")]
    Swedencentral,
    #[serde(rename = "switzerland")]
    Switzerland,
    #[serde(rename = "uk")]
    Uk,
    #[serde(rename = "westus")]
    Westus,
    #[serde(rename = "westus3")]
    Westus3,

}

impl std::fmt::Display for CreateAzureOpenAiCredentialDtoRegion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Australia => write!(f, "australia"),
            Self::Canadaeast => write!(f, "canadaeast"),
            Self::Canadacentral => write!(f, "canadacentral"),
            Self::Eastus2 => write!(f, "eastus2"),
            Self::Eastus => write!(f, "eastus"),
            Self::France => write!(f, "france"),
            Self::India => write!(f, "india"),
            Self::Japaneast => write!(f, "japaneast"),
            Self::Japanwest => write!(f, "japanwest"),
            Self::Uaenorth => write!(f, "uaenorth"),
            Self::Northcentralus => write!(f, "northcentralus"),
            Self::Norway => write!(f, "norway"),
            Self::Southcentralus => write!(f, "southcentralus"),
            Self::Swedencentral => write!(f, "swedencentral"),
            Self::Switzerland => write!(f, "switzerland"),
            Self::Uk => write!(f, "uk"),
            Self::Westus => write!(f, "westus"),
            Self::Westus3 => write!(f, "westus3"),
        }
    }
}

impl Default for CreateAzureOpenAiCredentialDtoRegion {
    fn default() -> CreateAzureOpenAiCredentialDtoRegion {
        Self::Australia
    }
}

