/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateToolTemplateDtoDetails {
    CreateDtmfToolDto(models::CreateDtmfToolDto),
    CreateEndCallToolDto(models::CreateEndCallToolDto),
    CreateVoicemailToolDto(models::CreateVoicemailToolDto),
    CreateFunctionToolDto(models::CreateFunctionToolDto),
    CreateGhlToolDto(models::CreateGhlToolDto),
    CreateMakeToolDto(models::CreateMakeToolDto),
    CreateTransferCallToolDto(models::CreateTransferCallToolDto),
    CreateGoogleCalendarCreateEventToolDto(models::CreateGoogleCalendarCreateEventToolDto),
    CreateGoogleSheetsRowAppendToolDto(models::CreateGoogleSheetsRowAppendToolDto),
}

impl Default for CreateToolTemplateDtoDetails {
    fn default() -> Self {
        Self::CreateDtmfToolDto(Default::default())
    }
}
/// The type of tool. \"dtmf\" for DTMF tool.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dtmf")]
    Dtmf,
    #[serde(rename = "endCall")]
    EndCall,
    #[serde(rename = "voicemail")]
    Voicemail,
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "ghl")]
    Ghl,
    #[serde(rename = "make")]
    Make,
    #[serde(rename = "transferCall")]
    TransferCall,
    #[serde(rename = "google.calendar.event.create")]
    GooglePeriodCalendarPeriodEventPeriodCreate,
    #[serde(rename = "google.sheets.row.append")]
    GooglePeriodSheetsPeriodRowPeriodAppend,
}

impl Default for Type {
    fn default() -> Type {
        Self::Dtmf
    }
}

