/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialEndUser {
    #[serde(rename = "endUserId")]
    pub end_user_id: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
}

impl CredentialEndUser {
    pub fn new(end_user_id: String, organization_id: String) -> CredentialEndUser {
        CredentialEndUser {
            end_user_id,
            organization_id,
        }
    }
}

