/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialSessionResponse {
    #[serde(rename = "sessionToken")]
    pub session_token: String,
}

impl CredentialSessionResponse {
    pub fn new(session_token: String) -> CredentialSessionResponse {
        CredentialSessionResponse { session_token }
    }
}
