/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialSessionError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl CredentialSessionError {
    pub fn new(r#type: String, description: String) -> CredentialSessionError {
        CredentialSessionError {
            r#type,
            description,
        }
    }
}
