/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeepgramTranscriber {
    /// This is the transcription provider that will be used.
    #[serde(rename = "provider")]
    pub provider: ProviderTrue,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<models::DeepgramTranscriberModel>,
    /// This is the language that will be set for the transcription. The list of languages Deepgram supports can be found here: https://developers.deepgram.com/docs/models-languages-overview
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageTrue>,
    /// This will be use smart format option provided by Deepgram. It's default disabled because it can sometimes format numbers as times but it's getting better.
    #[serde(rename = "smartFormat", skip_serializing_if = "Option::is_none")]
    pub smart_format: Option<bool>,
    /// This automatically switches the transcriber's language when the customer's language changes. Defaults to false.  Usage: - If your customers switch languages mid-call, you can set this to true.  Note: - To detect language changes, Vapi uses a custom trained model. Languages supported (X = limited support):   1. Arabic   2. Bengali   3. Cantonese   4. Chinese   5. Chinese Simplified (X)   6. Chinese Traditional (X)   7. English   8. Farsi (X)   9. French   10. German   11. Haitian Creole (X)   12. Hindi   13. Italian   14. Japanese   15. Korean   16. Portuguese   17. Russian   18. Spanish   19. Thai   20. Urdu   21. Vietnamese - To receive `language-change-detected` webhook events, add it to `assistant.serverMessages`.  @default false
    #[serde(rename = "codeSwitchingEnabled", skip_serializing_if = "Option::is_none")]
    pub code_switching_enabled: Option<bool>,
    /// If set to true, this will add mip_opt_out=true as a query parameter of all API requests. See https://developers.deepgram.com/docs/the-deepgram-model-improvement-partnership-program#want-to-opt-out  This will only be used if you are using your own Deepgram API key.  @default false
    #[serde(rename = "mipOptOut", skip_serializing_if = "Option::is_none")]
    pub mip_opt_out: Option<bool>,
    /// If set to true, this will cause deepgram to convert spoken numbers to literal numerals. For example, \"my phone number is nine-seven-two...\" would become \"my phone number is 972...\"  @default false
    #[serde(rename = "numerals", skip_serializing_if = "Option::is_none")]
    pub numerals: Option<bool>,
    /// Transcripts below this confidence threshold will be discarded.  @default 0.4
    #[serde(rename = "confidenceThreshold", skip_serializing_if = "Option::is_none")]
    pub confidence_threshold: Option<f64>,
    /// These keywords are passed to the transcription model to help it pick up use-case specific words. Anything that may not be a common word, like your company name, should be added here.
    #[serde(rename = "keywords", skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Vec<String>>,
    /// Keyterm Prompting allows you improve Keyword Recall Rate (KRR) for important keyterms or phrases up to 90%.
    #[serde(rename = "keyterm", skip_serializing_if = "Option::is_none")]
    pub keyterm: Option<Vec<String>>,
    /// This is the timeout after which Deepgram will send transcription on user silence. You can read in-depth documentation here: https://developers.deepgram.com/docs/endpointing.  Here are the most important bits: - Defaults to 10. This is recommended for most use cases to optimize for latency. - 10 can cause some missing transcriptions since because of the shorter context. This mostly happens for one-word utterances. For those uses cases, it's recommended to try 300. It will add a bit of latency but the quality and reliability of the experience will be better. - If neither 10 nor 300 work, contact support@vapi.ai and we'll find another solution.  @default 10
    #[serde(rename = "endpointing", skip_serializing_if = "Option::is_none")]
    pub endpointing: Option<f64>,
    /// This is the plan for voice provider fallbacks in the event that the primary voice provider fails.
    #[serde(rename = "fallbackPlan", skip_serializing_if = "Option::is_none")]
    pub fallback_plan: Option<models::FallbackTranscriberPlan>,
}

impl DeepgramTranscriber {
    pub fn new(provider: ProviderTrue) -> DeepgramTranscriber {
        DeepgramTranscriber {
            provider,
            model: None,
            language: None,
            smart_format: None,
            code_switching_enabled: None,
            mip_opt_out: None,
            numerals: None,
            confidence_threshold: None,
            keywords: None,
            keyterm: None,
            endpointing: None,
            fallback_plan: None,
        }
    }
}
/// This is the transcription provider that will be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProviderTrue {
    #[serde(rename = "deepgram")]
    Deepgram,
}

impl Default for ProviderTrue {
    fn default() -> ProviderTrue {
        Self::Deepgram
    }
}
/// This is the language that will be set for the transcription. The list of languages Deepgram supports can be found here: https://developers.deepgram.com/docs/models-languages-overview
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LanguageTrue {
    #[serde(rename = "ar")]
    Ar,
    #[serde(rename = "az")]
    Az,
    #[serde(rename = "ba")]
    Ba,
    #[serde(rename = "bg")]
    Bg,
    #[serde(rename = "br")]
    Br,
    #[serde(rename = "ca")]
    Ca,
    #[serde(rename = "cs")]
    Cs,
    #[serde(rename = "da")]
    Da,
    #[serde(rename = "da-DK")]
    DaDk,
    #[serde(rename = "de")]
    De,
    #[serde(rename = "de-CH")]
    DeCh,
    #[serde(rename = "el")]
    El,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "en-AU")]
    EnAu,
    #[serde(rename = "en-GB")]
    EnGb,
    #[serde(rename = "en-IN")]
    EnIn,
    #[serde(rename = "en-NZ")]
    EnNz,
    #[serde(rename = "en-US")]
    EnUs,
    #[serde(rename = "es")]
    Es,
    #[serde(rename = "es-419")]
    Es419,
    #[serde(rename = "es-LATAM")]
    EsLatam,
    #[serde(rename = "et")]
    Et,
    #[serde(rename = "eu")]
    Eu,
    #[serde(rename = "fi")]
    Fi,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "fr-CA")]
    FrCa,
    #[serde(rename = "ha")]
    Ha,
    #[serde(rename = "haw")]
    Haw,
    #[serde(rename = "he")]
    He,
    #[serde(rename = "hi")]
    Hi,
    #[serde(rename = "hi-Latn")]
    HiLatn,
    #[serde(rename = "hu")]
    Hu,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "is")]
    Is,
    #[serde(rename = "it")]
    It,
    #[serde(rename = "ja")]
    Ja,
    #[serde(rename = "jw")]
    Jw,
    #[serde(rename = "kn")]
    Kn,
    #[serde(rename = "ko")]
    Ko,
    #[serde(rename = "ko-KR")]
    KoKr,
    #[serde(rename = "ln")]
    Ln,
    #[serde(rename = "lt")]
    Lt,
    #[serde(rename = "lv")]
    Lv,
    #[serde(rename = "mk")]
    Mk,
    #[serde(rename = "ms")]
    Ms,
    #[serde(rename = "multi")]
    Multi,
    #[serde(rename = "nl")]
    Nl,
    #[serde(rename = "nl-BE")]
    NlBe,
    #[serde(rename = "no")]
    No,
    #[serde(rename = "pl")]
    Pl,
    #[serde(rename = "pt")]
    Pt,
    #[serde(rename = "pt-BR")]
    PtBr,
    #[serde(rename = "ro")]
    Ro,
    #[serde(rename = "ru")]
    Ru,
    #[serde(rename = "sk")]
    Sk,
    #[serde(rename = "sl")]
    Sl,
    #[serde(rename = "sn")]
    Sn,
    #[serde(rename = "so")]
    So,
    #[serde(rename = "sr")]
    Sr,
    #[serde(rename = "su")]
    Su,
    #[serde(rename = "sv")]
    Sv,
    #[serde(rename = "sv-SE")]
    SvSe,
    #[serde(rename = "ta")]
    Ta,
    #[serde(rename = "taq")]
    Taq,
    #[serde(rename = "th")]
    Th,
    #[serde(rename = "th-TH")]
    ThTh,
    #[serde(rename = "tr")]
    Tr,
    #[serde(rename = "tt")]
    Tt,
    #[serde(rename = "uk")]
    Uk,
    #[serde(rename = "ur")]
    Ur,
    #[serde(rename = "vi")]
    Vi,
    #[serde(rename = "yo")]
    Yo,
    #[serde(rename = "zh")]
    Zh,
    #[serde(rename = "zh-CN")]
    ZhCn,
    #[serde(rename = "zh-HK")]
    ZhHk,
    #[serde(rename = "zh-Hans")]
    ZhHans,
    #[serde(rename = "zh-Hant")]
    ZhHant,
    #[serde(rename = "zh-TW")]
    ZhTw,
}

impl Default for LanguageTrue {
    fn default() -> LanguageTrue {
        Self::Ar
    }
}

