/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FallbackVapiVoice {
    #[serde(rename = "voiceId")]
    pub voice_id: models::FallbackVapiVoiceVoiceId,
    /// This is the speed multiplier that will be used.  @default 1
    #[serde(rename = "speed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub speed: Option<Option<f64>>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<models::FallbackVapiVoiceLanguage>,
    #[serde(rename = "chunkPlan", skip_serializing_if = "Option::is_none")]
    pub chunk_plan: Option<models::ChunkPlan>,
}

impl FallbackVapiVoice {
    pub fn new(voice_id: models::FallbackVapiVoiceVoiceId) -> FallbackVapiVoice {
        FallbackVapiVoice {
            voice_id,
            speed: None,
            language: None,
            chunk_plan: None,
        }
    }
}

