/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use utoipa::OpenApi;


use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, OpenApi)]
pub struct FallbackPlan {
    /// This is the list of voices to fallback to in the event that the primary voice provider fails.
    #[serde(rename = "voices")]
    pub voices: Vec<models::FallbackPlanVoicesInner>,
}

impl FallbackPlan {
    pub fn new(voices: Vec<models::FallbackPlanVoicesInner>) -> FallbackPlan {
        FallbackPlan { voices }
    }
}
