/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FallbackOpenAiTranscriber {
    #[serde(rename = "model")]
    pub model: models::FallbackOpenAiTranscriberModel,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<models::FallbackOpenAiTranscriberLanguage>,
}

impl FallbackOpenAiTranscriber {
    pub fn new(model: models::FallbackOpenAiTranscriberModel) -> FallbackOpenAiTranscriber {
        FallbackOpenAiTranscriber {
            model,
            language: None,
        }
    }
}

