/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;


use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct GeminiMultimodalLiveSpeechConfig {
    #[serde(rename = "voiceConfig")]
    pub voice_config: models::GeminiMultimodalLiveVoiceConfig,
}

impl GeminiMultimodalLiveSpeechConfig {
    pub fn new(
        voice_config: models::GeminiMultimodalLiveVoiceConfig,
    ) -> GeminiMultimodalLiveSpeechConfig {
        GeminiMultimodalLiveSpeechConfig { voice_config }
    }
}
