/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GladiaTranscriberModel {
    #[serde(rename = "fast")]
    Fast,
    #[serde(rename = "accurate")]
    Accurate,

}

impl std::fmt::Display for GladiaTranscriberModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fast => write!(f, "fast"),
            Self::Accurate => write!(f, "accurate"),
        }
    }
}

impl Default for GladiaTranscriberModel {
    fn default() -> GladiaTranscriberModel {
        Self::Fast
    }
}

