/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImportTwilioPhoneNumberDtoHooksInner {
    PhoneNumberHookCallRinging(models::PhoneNumberHookCallRinging),
}

impl Default for ImportTwilioPhoneNumberDtoHooksInner {
    fn default() -> Self {
        Self::PhoneNumberHookCallRinging(Default::default())
    }
}
/// This is the event to trigger the hook on
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnTrue {
    #[serde(rename = "call.ringing")]
    CallPeriodRinging,
}

impl Default for OnTrue {
    fn default() -> OnTrue {
        Self::CallPeriodRinging
    }
}
