/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum KnowledgeBasesUpdateRequest {
    KnowledgeBasesUpdateRequestOneOf(Box<models::KnowledgeBasesUpdateRequestOneOf>),
    KnowledgeBasesUpdateRequestOneOf1(Box<models::KnowledgeBasesUpdateRequestOneOf1>),
}

impl Default for KnowledgeBasesUpdateRequest {
    fn default() -> Self {
        Self::KnowledgeBasesUpdateRequestOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "custom-knowledge-base")]
    CustomKnowledgeBase,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::CustomKnowledgeBase
    }
}

