/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageArrayInner {
    SystemMessage(models::SystemMessage),
    UserMessage(models::UserMessage),
    AssistantMessage(models::AssistantMessage),
    ToolMessage(models::ToolMessage),
    DeveloperMessage(models::DeveloperMessage),
}

impl Default for MessageArrayInner {
    fn default() -> Self {
        Self::SystemMessage(Default::default())
    }
}
/// This is the role of the message author
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoleTrue {
    #[serde(rename = "developer")]
    Developer,
}

impl Default for RoleTrue {
    fn default() -> RoleTrue {
        Self::Developer
    }
}

