/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use utoipa::OpenApi;


use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, OpenApi)]
pub struct OAuth2AuthenticationPlan {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// This is the OAuth2 URL.
    #[serde(rename = "url")]
    pub url: String,
    /// This is the OAuth2 client ID.
    #[serde(rename = "clientId")]
    pub client_id: String,
    /// This is the OAuth2 client secret.
    #[serde(rename = "clientSecret")]
    pub client_secret: String,
    /// This is the scope of the OAuth2 token.
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl OAuth2AuthenticationPlan {
    pub fn new(
        r#type: Type,
        url: String,
        client_id: String,
        client_secret: String,
    ) -> OAuth2AuthenticationPlan {
        OAuth2AuthenticationPlan {
            r#type,
            url,
            client_id,
            client_secret,
            scope: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, OpenApi)]
pub enum Type {
    #[serde(rename = "oauth2")]
    Oauth2,
}

impl Default for Type {
    fn default() -> Type {
        Self::Oauth2
    }
}
