/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiVoice {
    #[serde(rename = "voiceId")]
    pub voice_id: models::OpenAiVoiceId,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<models::OpenAiVoiceModel>,
    /// This is a prompt that allows you to control the voice of your generated audio. Does not work with 'tts-1' or 'tts-1-hd' models.
    #[serde(rename = "instructions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Option<String>>,
    /// This is the speed multiplier that will be used.
    #[serde(rename = "speed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub speed: Option<Option<f64>>,
    #[serde(rename = "chunkPlan", skip_serializing_if = "Option::is_none")]
    pub chunk_plan: Option<models::ChunkPlan>,
    #[serde(rename = "fallbackPlan", skip_serializing_if = "Option::is_none")]
    pub fallback_plan: Option<models::FallbackPlan>,
}

impl OpenAiVoice {
    pub fn new(voice_id: models::OpenAiVoiceId) -> OpenAiVoice {
        OpenAiVoice {
            voice_id,
            model: None,
            instructions: None,
            speed: None,
            chunk_plan: None,
            fallback_plan: None,
        }
    }
}

