/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchedulePlan {
    /// This is the ISO 8601 date-time string of the earliest time the call can be scheduled.
    #[serde(rename = "earliestAt")]
    pub earliest_at: String,
    /// This is the ISO 8601 date-time string of the latest time the call can be scheduled.
    #[serde(rename = "latestAt", skip_serializing_if = "Option::is_none")]
    pub latest_at: Option<String>,
}

impl SchedulePlan {
    pub fn new(earliest_at: String) -> SchedulePlan {
        SchedulePlan {
            earliest_at,
            latest_at: None,
        }
    }
}
