/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerMessageLanguageChangeDetected {
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<models::ClientMessageWorkflowNodeStartedPhoneNumber>,
    /// This is the type of the message. \"language-change-detected\" is sent when the transcriber is automatically switched based on the detected language.
    #[serde(rename = "type")]
    pub r#type: TypeTrue,
    /// This is the timestamp of the message.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
    /// This is a live version of the `call.artifact`.  This matches what is stored on `call.artifact` after the call.
    #[serde(rename = "artifact", skip_serializing_if = "Option::is_none")]
    pub artifact: Option<models::Artifact>,
    /// This is the assistant that the message is associated with.
    #[serde(rename = "assistant", skip_serializing_if = "Option::is_none")]
    pub assistant: Option<models::CreateAssistantDto>,
    /// This is the customer that the message is associated with.
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<models::CreateCustomerDto>,
    /// This is the call that the message is associated with.
    #[serde(rename = "call", skip_serializing_if = "Option::is_none")]
    pub call: Option<models::Call>,
    /// This is the chat object.
    #[serde(rename = "chat", skip_serializing_if = "Option::is_none")]
    pub chat: Option<models::Chat>,
    /// This is the language the transcriber is switched to.
    #[serde(rename = "language")]
    pub language: String,
}

impl ServerMessageLanguageChangeDetected {
    pub fn new(r#type: TypeTrue, language: String) -> ServerMessageLanguageChangeDetected {
        ServerMessageLanguageChangeDetected {
            phone_number: None,
            r#type,
            timestamp: None,
            artifact: None,
            assistant: None,
            customer: None,
            call: None,
            chat: None,
            language,
        }
    }
}
/// This is the type of the message. \"language-change-detected\" is sent when the transcriber is automatically switched based on the detected language.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeTrue {
    #[serde(rename = "language-change-detected")]
    LanguageChangeDetected,
}

impl Default for TypeTrue {
    fn default() -> TypeTrue {
        Self::LanguageChangeDetected
    }
}
