/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerMessageTranscript {
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<models::ServerMessageTranscriptPhoneNumber>,
    #[serde(rename = "type")]
    pub r#type: models::ServerMessageTranscriptType,
    /// This is the timestamp of when the message was sent in milliseconds since Unix Epoch.
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<f64>>,
    #[serde(rename = "artifact", skip_serializing_if = "Option::is_none")]
    pub artifact: Option<models::Artifact>,
    #[serde(rename = "assistant", skip_serializing_if = "Option::is_none")]
    pub assistant: Option<models::CreateAssistantDto>,
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<models::CreateCustomerDto>,
    #[serde(rename = "call", skip_serializing_if = "Option::is_none")]
    pub call: Option<models::Call>,
    #[serde(rename = "role")]
    pub role: models::ServerMessageTranscriptRole,
    #[serde(rename = "transcriptType")]
    pub transcript_type: models::ServerMessageTranscriptTranscriptType,
    /// This is the transcript content.
    #[serde(rename = "transcript")]
    pub transcript: String,
}

impl ServerMessageTranscript {
    pub fn new(r#type: models::ServerMessageTranscriptType, role: models::ServerMessageTranscriptRole, transcript_type: models::ServerMessageTranscriptTranscriptType, transcript: String) -> ServerMessageTranscript {
        ServerMessageTranscript {
            phone_number: None,
            r#type,
            timestamp: None,
            artifact: None,
            assistant: None,
            customer: None,
            call: None,
            role,
            transcript_type,
            transcript,
        }
    }
}

