/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SipTrunkOutboundSipRegisterPlan {
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "realm", skip_serializing_if = "Option::is_none")]
    pub realm: Option<String>,
}

impl SipTrunkOutboundSipRegisterPlan {
    pub fn new() -> SipTrunkOutboundSipRegisterPlan {
        SipTrunkOutboundSipRegisterPlan {
            domain: None,
            username: None,
            realm: None,
        }
    }
}
