/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SipTrunkOutboundAuthenticationPlan {
    /// This is not returned in the API.
    #[serde(rename = "authPassword", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_password: Option<Option<String>>,
    #[serde(rename = "authUsername", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_username: Option<Option<String>>,
    #[serde(rename = "sipRegisterPlan", skip_serializing_if = "Option::is_none")]
    pub sip_register_plan: Option<models::SipTrunkOutboundSipRegisterPlan>,
}

impl SipTrunkOutboundAuthenticationPlan {
    pub fn new() -> SipTrunkOutboundAuthenticationPlan {
        SipTrunkOutboundAuthenticationPlan {
            auth_password: None,
            auth_username: None,
            sip_register_plan: None,
        }
    }
}

