/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SipTrunkOutboundSipRegisterPlan {
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    #[serde(rename = "username", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub username: Option<Option<String>>,
    #[serde(rename = "realm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub realm: Option<Option<String>>,
}

impl SipTrunkOutboundSipRegisterPlan {
    pub fn new() -> SipTrunkOutboundSipRegisterPlan {
        SipTrunkOutboundSipRegisterPlan {
            domain: None,
            username: None,
            realm: None,
        }
    }
}

