/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscriptionType : This is the type / tier of the subscription.
/// This is the type / tier of the subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionType {
    #[serde(rename = "trial")]
    Trial,
    #[serde(rename = "pay-as-you-go")]
    PayAsYouGo,
    #[serde(rename = "enterprise")]
    Enterprise,

}

impl std::fmt::Display for SubscriptionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Trial => write!(f, "trial"),
            Self::PayAsYouGo => write!(f, "pay-as-you-go"),
            Self::Enterprise => write!(f, "enterprise"),
        }
    }
}

impl Default for SubscriptionType {
    fn default() -> SubscriptionType {
        Self::Trial
    }
}

