/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupabaseBucketPlanRegion : This is the S3 Region. It should look like us-east-1 It should be one of the supabase regions defined in the SUPABASE_REGION enum Check https://supabase.com/docs/guides/platform/regions for up to date regions
/// This is the S3 Region. It should look like us-east-1 It should be one of the supabase regions defined in the SUPABASE_REGION enum Check https://supabase.com/docs/guides/platform/regions for up to date regions
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupabaseBucketPlanRegion {
    #[serde(rename = "us-west-1")]
    UsWest1,
    #[serde(rename = "us-east-1")]
    UsEast1,
    #[serde(rename = "us-east-2")]
    UsEast2,
    #[serde(rename = "ca-central-1")]
    CaCentral1,
    #[serde(rename = "eu-west-1")]
    EuWest1,
    #[serde(rename = "eu-west-2")]
    EuWest2,
    #[serde(rename = "eu-west-3")]
    EuWest3,
    #[serde(rename = "eu-central-1")]
    EuCentral1,
    #[serde(rename = "eu-central-2")]
    EuCentral2,
    #[serde(rename = "eu-north-1")]
    EuNorth1,
    #[serde(rename = "ap-south-1")]
    ApSouth1,
    #[serde(rename = "ap-southeast-1")]
    ApSoutheast1,
    #[serde(rename = "ap-northeast-1")]
    ApNortheast1,
    #[serde(rename = "ap-northeast-2")]
    ApNortheast2,
    #[serde(rename = "ap-southeast-2")]
    ApSoutheast2,
    #[serde(rename = "sa-east-1")]
    SaEast1,

}

impl std::fmt::Display for SupabaseBucketPlanRegion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UsWest1 => write!(f, "us-west-1"),
            Self::UsEast1 => write!(f, "us-east-1"),
            Self::UsEast2 => write!(f, "us-east-2"),
            Self::CaCentral1 => write!(f, "ca-central-1"),
            Self::EuWest1 => write!(f, "eu-west-1"),
            Self::EuWest2 => write!(f, "eu-west-2"),
            Self::EuWest3 => write!(f, "eu-west-3"),
            Self::EuCentral1 => write!(f, "eu-central-1"),
            Self::EuCentral2 => write!(f, "eu-central-2"),
            Self::EuNorth1 => write!(f, "eu-north-1"),
            Self::ApSouth1 => write!(f, "ap-south-1"),
            Self::ApSoutheast1 => write!(f, "ap-southeast-1"),
            Self::ApNortheast1 => write!(f, "ap-northeast-1"),
            Self::ApNortheast2 => write!(f, "ap-northeast-2"),
            Self::ApSoutheast2 => write!(f, "ap-southeast-2"),
            Self::SaEast1 => write!(f, "sa-east-1"),
        }
    }
}

impl Default for SupabaseBucketPlanRegion {
    fn default() -> SupabaseBucketPlanRegion {
        Self::UsWest1
    }
}

