/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TavusVoiceVoiceId : This is the provider-specific ID that will be used.
/// This is the provider-specific ID that will be used.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TavusVoiceVoiceId {
    PresetVoiceOptions(String),
    TavusVoiceId(String),
}

impl Default for TavusVoiceVoiceId {
    fn default() -> Self {
        Self::PresetVoiceOptions(Default::default())
    }
}
