/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TesterPlan {
    /// Pass a transient assistant to use for the test assistant.  Make sure to write a detailed system prompt for a test assistant, and use the {{test.script}} variable to access the test script.
    #[serde(rename = "assistant", skip_serializing_if = "Option::is_none")]
    pub assistant: Option<models::CreateAssistantDto>,
    /// Pass an assistant id that can be access  Make sure to write a detailed system prompt for the test assistant, and use the {{test.script}} variable to access the test script.
    #[serde(rename = "assistantId", skip_serializing_if = "Option::is_none")]
    pub assistant_id: Option<String>,
    /// Add any assistant overrides to the test assistant.  One use case is if you want to pass custom variables into the test using variableValues, that you can then access in the script and rubric using {{varName}}.
    #[serde(rename = "assistantOverrides", skip_serializing_if = "Option::is_none")]
    pub assistant_overrides: Option<models::AssistantOverrides>,
}

impl TesterPlan {
    pub fn new() -> TesterPlan {
        TesterPlan {
            assistant: None,
            assistant_id: None,
            assistant_overrides: None,
        }
    }
}

