/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;


use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
#[serde(untagged)]
pub enum TestSuiteTestVoiceScorersInner {
    TestSuiteTestScorerAi(models::TestSuiteTestScorerAi),
}

impl Default for TestSuiteTestVoiceScorersInner {
    fn default() -> Self {
        Self::TestSuiteTestScorerAi(Default::default())
    }
}
/// This is the type of the scorer, which must be AI.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, ToSchema)]
pub enum Type {
    #[serde(rename = "ai")]
    Ai,
}

impl Default for Type {
    fn default() -> Type {
        Self::Ai
    }
}
