/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestSuiteRunsPaginatedResponse {
    #[serde(rename = "results")]
    pub results: Vec<models::TestSuiteRun>,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::PaginationMeta>,
}

impl TestSuiteRunsPaginatedResponse {
    pub fn new(results: Vec<models::TestSuiteRun>, metadata: models::PaginationMeta) -> TestSuiteRunsPaginatedResponse {
        TestSuiteRunsPaginatedResponse {
            results,
            metadata: Box::new(metadata),
        }
    }
}

