/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TestSuiteTestControllerCreate201Response {
    #[serde(rename = "voice")]
    Voice(models::TestSuiteTestVoice),
    #[serde(rename = "chat")]
    Chat(models::TestSuiteTestChat),
}

impl Default for TestSuiteTestControllerCreate201Response {
    fn default() -> Self {
        Self::Voice(Default::default())
    }
}
