/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestSuitesPaginatedResponse {
    #[serde(rename = "results")]
    pub results: Vec<models::TestSuite>,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::PaginationMeta>,
}

impl TestSuitesPaginatedResponse {
    pub fn new(results: Vec<models::TestSuite>, metadata: models::PaginationMeta) -> TestSuitesPaginatedResponse {
        TestSuitesPaginatedResponse {
            results,
            metadata: Box::new(metadata),
        }
    }
}

