/*
 * Vapi API
 *
 * API for building voice assistants
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use utoipa::OpenApi;


use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, OpenApi)]
pub struct ToolCall {
    /// This is the type of tool the model called.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// This is the function the model called.
    #[serde(rename = "function")]
    pub function: models::ToolCallFunction,
    /// This is the unique identifier for the tool call.
    #[serde(rename = "id")]
    pub id: String,
}

impl ToolCall {
    pub fn new(r#type: Type, function: models::ToolCallFunction, id: String) -> ToolCall {
        ToolCall {
            r#type,
            function,
            id,
        }
    }
}
/// This is the type of tool the model called.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, OpenApi)]
pub enum Type {
    #[serde(rename = "function")]
    Function,
}

impl Default for Type {
    fn default() -> Type {
        Self::Function
    }
}
