/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransferCallToolDestinationsItem {
    CreateTransferCallToolDtoDestinationsItemOneOf(models::CreateTransferCallToolDtoDestinationsItemOneOf),
    CreateTransferCallToolDtoDestinationsItemOneOf1(models::CreateTransferCallToolDtoDestinationsItemOneOf1),
    CreateTransferCallToolDtoDestinationsItemOneOf2(models::CreateTransferCallToolDtoDestinationsItemOneOf2),
    CreateTransferCallToolDtoDestinationsItemOneOf3(models::CreateTransferCallToolDtoDestinationsItemOneOf3),
}

impl Default for TransferCallToolDestinationsItem {
    fn default() -> Self {
        Self::CreateTransferCallToolDtoDestinationsItemOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "step")]
    Step,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "sip")]
    Sip,
}

impl Default for Type {
    fn default() -> Type {
        Self::Assistant
    }
}

