/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrieveKnowledgeBaseSearchPlan {
    /// Specifies the number of top chunks to return. This corresponds to the `page_size` parameter in Trieve.
    #[serde(rename = "topK", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub top_k: Option<Option<f64>>,
    /// If true, stop words (specified in server/src/stop-words.txt in the git repo) will be removed. This will preserve queries that are entirely stop words.
    #[serde(rename = "removeStopWords", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remove_stop_words: Option<Option<bool>>,
    /// This is the score threshold to filter out chunks with a score below the threshold for cosine distance metric. For Manhattan Distance, Euclidean Distance, and Dot Product, it will filter out scores above the threshold distance. This threshold applies before weight and bias modifications. If not specified, this defaults to no threshold. A threshold of 0 will default to no threshold.
    #[serde(rename = "scoreThreshold", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score_threshold: Option<Option<f64>>,
    #[serde(rename = "searchType")]
    pub search_type: models::TrieveKnowledgeBaseSearchPlanSearchType,
}

impl TrieveKnowledgeBaseSearchPlan {
    pub fn new(search_type: models::TrieveKnowledgeBaseSearchPlanSearchType) -> TrieveKnowledgeBaseSearchPlan {
        TrieveKnowledgeBaseSearchPlan {
            top_k: None,
            remove_stop_words: None,
            score_threshold: None,
            search_type,
        }
    }
}

