/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TwilioPhoneNumberStatus : This is the status of the phone number.
/// This is the status of the phone number.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwilioPhoneNumberStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "activating")]
    Activating,
    #[serde(rename = "blocked")]
    Blocked,

}

impl std::fmt::Display for TwilioPhoneNumberStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "active"),
            Self::Activating => write!(f, "activating"),
            Self::Blocked => write!(f, "blocked"),
        }
    }
}

impl Default for TwilioPhoneNumberStatus {
    fn default() -> TwilioPhoneNumberStatus {
        Self::Active
    }
}

