/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebhookCredentialDto {
    #[serde(rename = "authenticationPlan", skip_serializing_if = "Option::is_none")]
    pub authentication_plan: Option<models::OAuth2AuthenticationPlan>,
    /// This is the name of credential. This is just for your reference.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl UpdateWebhookCredentialDto {
    pub fn new() -> UpdateWebhookCredentialDto {
        UpdateWebhookCredentialDto {
            authentication_plan: None,
            name: None,
        }
    }
}

