/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWorkflowDtoNodesItemOneOf3 {
    #[serde(rename = "name")]
    pub name: String,
    /// This is for metadata you want to store on the task.
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl UpdateWorkflowDtoNodesItemOneOf3 {
    pub fn new(name: String, r#type: Type) -> UpdateWorkflowDtoNodesItemOneOf3 {
        UpdateWorkflowDtoNodesItemOneOf3 {
            name,
            metadata: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "hangup")]
    Hangup,
}

impl Default for Type {
    fn default() -> Type {
        Self::Hangup
    }
}

