/*
 * Vapi API
 *
 * Voice AI for developers.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGoHighLevelMcpCredentialDto {
    /// This is the authentication session for the credential.
    #[serde(
        rename = "authenticationSession",
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_session: Option<models::Oauth2AuthenticationSession>,
    /// This is the name of credential. This is just for your reference.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateGoHighLevelMcpCredentialDto {
    pub fn new() -> UpdateGoHighLevelMcpCredentialDto {
        UpdateGoHighLevelMcpCredentialDto {
            authentication_session: None,
            name: None,
        }
    }
}
