/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAssistantDtoVoiceOneOf7 {
    /// This is the provider-specific ID that will be used.
    #[serde(rename = "voiceId")]
    pub voice_id: String,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<models::NeuphonicVoiceModel>,
    /// This is the language (ISO 639-1) that is enforced for the model.
    #[serde(rename = "language")]
    pub language: std::collections::HashMap<String, serde_json::Value>,
    /// This is the speed multiplier that will be used.
    #[serde(rename = "speed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub speed: Option<Option<f64>>,
    #[serde(rename = "chunkPlan", skip_serializing_if = "Option::is_none")]
    pub chunk_plan: Option<models::ChunkPlan>,
    #[serde(rename = "fallbackPlan", skip_serializing_if = "Option::is_none")]
    pub fallback_plan: Option<models::FallbackPlan>,
    #[serde(rename = "provider")]
    pub provider: Provider,
}

impl UpdateAssistantDtoVoiceOneOf7 {
    pub fn new(voice_id: String, language: std::collections::HashMap<String, serde_json::Value>, provider: Provider) -> UpdateAssistantDtoVoiceOneOf7 {
        UpdateAssistantDtoVoiceOneOf7 {
            voice_id,
            model: None,
            language,
            speed: None,
            chunk_plan: None,
            fallback_plan: None,
            provider,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "neuphonic")]
    Neuphonic,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Neuphonic
    }
}

