/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateWorkflowDtoNodesItem {
    UpdateWorkflowDtoNodesItemOneOf(Box<models::UpdateWorkflowDtoNodesItemOneOf>),
    UpdateWorkflowDtoNodesItemOneOf1(Box<models::UpdateWorkflowDtoNodesItemOneOf1>),
    UpdateWorkflowDtoNodesItemOneOf2(Box<models::UpdateWorkflowDtoNodesItemOneOf2>),
    UpdateWorkflowDtoNodesItemOneOf3(Box<models::UpdateWorkflowDtoNodesItemOneOf3>),
    UpdateWorkflowDtoNodesItemOneOf4(Box<models::UpdateWorkflowDtoNodesItemOneOf4>),
}

impl Default for UpdateWorkflowDtoNodesItem {
    fn default() -> Self {
        Self::UpdateWorkflowDtoNodesItemOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "say")]
    Say,
    #[serde(rename = "gather")]
    Gather,
    #[serde(rename = "apiRequest")]
    ApiRequest,
    #[serde(rename = "hangup")]
    Hangup,
    #[serde(rename = "transfer")]
    Transfer,
}

impl Default for Type {
    fn default() -> Type {
        Self::Say
    }
}

