/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAssistantDtoCredentialsItemOneOf10 {
    /// This is not returned in the API.
    #[serde(rename = "apiKey")]
    pub api_key: String,
    #[serde(rename = "authenticationPlan", skip_serializing_if = "Option::is_none")]
    pub authentication_plan: Option<models::OAuth2AuthenticationPlan>,
    /// This is the name of credential. This is just for your reference.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "provider")]
    pub provider: Provider,
}

impl UpdateAssistantDtoCredentialsItemOneOf10 {
    pub fn new(api_key: String, provider: Provider) -> UpdateAssistantDtoCredentialsItemOneOf10 {
        UpdateAssistantDtoCredentialsItemOneOf10 {
            api_key,
            authentication_plan: None,
            name: None,
            provider,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "custom-llm")]
    CustomLlm,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::CustomLlm
    }
}

