/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VapiSmartEndpointingPlan {
    #[serde(rename = "provider")]
    pub provider: models::VapiSmartEndpointingPlanProvider,
}

impl VapiSmartEndpointingPlan {
    pub fn new(provider: models::VapiSmartEndpointingPlanProvider) -> VapiSmartEndpointingPlan {
        VapiSmartEndpointingPlan {
            provider,
        }
    }
}

