/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VoicemailDetectionCostProvider : This is the provider that was used to detect the voicemail.
/// This is the provider that was used to detect the voicemail.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VoicemailDetectionCostProvider {
    #[serde(rename = "twilio")]
    Twilio,
    #[serde(rename = "google")]
    Google,
    #[serde(rename = "openai")]
    Openai,

}

impl std::fmt::Display for VoicemailDetectionCostProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Twilio => write!(f, "twilio"),
            Self::Google => write!(f, "google"),
            Self::Openai => write!(f, "openai"),
        }
    }
}

impl Default for VoicemailDetectionCostProvider {
    fn default() -> VoicemailDetectionCostProvider {
        Self::Twilio
    }
}

