/*
 * Vapi API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VoiceLibraryGender : The gender of the voice.
/// The gender of the voice.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VoiceLibraryGender {
    #[serde(rename = "male")]
    Male,
    #[serde(rename = "female")]
    Female,

}

impl std::fmt::Display for VoiceLibraryGender {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Male => write!(f, "male"),
            Self::Female => write!(f, "female"),
        }
    }
}

impl Default for VoiceLibraryGender {
    fn default() -> VoiceLibraryGender {
        Self::Male
    }
}

